//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class SimulationLog
    {
        public int Id { get; set; }
        public int SimulationId { get; set; }
        public int NodeId { get; set; }
        public int IterationNumber { get; set; }
        public int Type { get; set; }
        public string Content { get; set; }
    }
}
